name: Update Recipes

on:
  push:
    branches:
      - main

jobs:
  update-recipes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update recipes.json
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          echo '{"recipes": []}' > recipes.json
          git add recipes.json
          git commit -m "Update recipes.json" || true
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
